#!/bin/sh

if [ "`git rev-parse --abbrev-ref HEAD`" = "master" ]
then
    exec < /dev/tty;
    read -p "[post-commit hook] Are you sure you want to commit to master? (Y/n) " yn
    if [ "$yn" = "" ]; then
        echo -n "No";
        yn='n';
    fi
    case $yn in
        [Yy] ) exit 0;;
        [Nn] ) echo "Abandoning"; exit 1;;
    esac
fi
exit 0;
